spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/autoquickrepairdatabase
    username: root
    password: Lsy200304144815
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  port: 8011
#aliyun:
#  sms:
#    sms-access-key-id:
#    sms-access-key-secret:
#    sms-endpoint:
#    sms-template-code:
#    sms-sign-name: