spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< HEAD
    url:
    username:
=======
    url: jdbc:mysql://localhost:3306/autoquickrepairdatabase
    username: root
>>>>>>> f6bfeb0 (员工接口+公共接口)
    password:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
server:
  port: 8011
